name: HackRF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ubuntu-build:
    name: Build for ubuntu-22.04
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
    - name: Build frontend
      run: |
        cd frontend
        npm run deploy

    - name: Build with Pyinstaller
      run: |
        pyinstaller --distpath app --onefile backend/main.py
        cp -r backend/app/static app

    - name: Prepare artifact directory
      run: |
        mkdir hrf_ubuntu
        mv app hrf_ubuntu/
        mv build hrf_ubuntu/
        mv main.spec hrf_ubuntu/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hrf_ubuntu
        path: hrf_ubuntu/
        if-no-files-found: warn
        retention-days: 90
        compression-level: 6
        overwrite: false